//
//  patientData.swift
//  MyHealthApp
//
//  Created by Kelly Bonilla Guzmán on 1/19/25.
//

import Foundation

var patientData: [Patient] = [
	Patient(firstName: "John",
			lastName: "Doe",
			dateOfBirth: DateFactory.createDateFromComponents(calendar: Calendar.current,
															  year: 2000,
															  month: 1,
															  day: 1),
			height: Measurement(value: 6.0, unit: UnitLength.feet),
			weight: Measurement(value: 200, unit: UnitMass.pounds),
			bloodType: BloodType.bNegative,
			medications: [metoprolol, aspirin, losartan]),
	Patient(firstName: "Jane",
			lastName: "Roe",
			dateOfBirth: DateFactory.createDateFromComponents(calendar: Calendar.current,
															  year: 2001,
															  month: 1,
															  day: 1),
			height: Measurement(value: 5.6, unit: UnitLength.feet),
			weight: Measurement(value: 160, unit: UnitMass.pounds),
			bloodType: BloodType.oPositive,
			medications: []),
	Patient(firstName: "Kelly",
			lastName: "Bonilla Guzmán",
			dateOfBirth: DateFactory.createDateFromComponents(calendar: Calendar.current,
															  year: 2002,
															  month: 1,
															  day: 1),
			height: Measurement(value: 5.8, unit: UnitLength.feet),
			weight: Measurement(value: 180, unit: UnitMass.pounds),
			bloodType: BloodType.abPositive,
			medications: []),
	Patient(firstName: "Mahmood",
			lastName: "Sadeghi",
			dateOfBirth: DateFactory.createDateFromComponents(calendar: Calendar.current,
															  year: 2003,
															  month: 1,
															  day: 1),
			height: Measurement(value: 5.8, unit: UnitLength.feet),
			weight: Measurement(value: 180, unit: UnitMass.pounds),
			bloodType: BloodType.abPositive,
			medications: []),
	Patient(firstName: "Lindsey",
			lastName: "Cruz Rosales",
			dateOfBirth: DateFactory.createDateFromComponents(calendar: Calendar.current,
															  year: 2004,
															  month: 1,
															  day: 1),
			height: Measurement(value: 5.8, unit: UnitLength.feet),
			weight: Measurement(value: 180, unit: UnitMass.pounds),
			bloodType: BloodType.abPositive,
			medications: []),
	Patient(firstName: "Edward",
			lastName: "Chanquin",
			dateOfBirth: DateFactory.createDateFromComponents(calendar: Calendar.current,
															  year: 2005,
															  month: 1,
															  day: 1),
			height: Measurement(value: 5.8, unit: UnitLength.feet),
			weight: Measurement(value: 180, unit: UnitMass.pounds),
			bloodType: BloodType.abPositive,
			medications: [])
]
